site_name: Jogo Digital - Grupo 1
site_url: https://unbarqdsw2025-2-turma01.github.io/2025.2-T01-G1_JogoDigital_Entrega_02/

repo_url: https://unbarqdsw2025-2-turma01.github.io/2025.2-T01-G1_JogoDigital_Entrega_02/
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://unbarqdsw2025-2-turma01.github.io/2025.2-T01-G1_JogoDigital_Entrega_02/

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple    
      accent: pink        
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

nav:
  - Apresentação: README.md
  - Atas Reunião:
    - Entrega 02: 
        Atas/Ata I.md
        Atas/Ata II.md
        Atas/Ata III.md
  - 2. Desenho de Software (Modelagem):
      - 2. Modelagem Geral: Modelagem/2.Modelagem.md
      - 2.1. Modelagem UML Estática: Modelagem/2.1.ModelagemEstatica.md
      - 2.2. Modelagem UML Dinâmica: Modelagem/2.2.ModelagemDinamica.md
      - 2.3. Modelagem UML Organizacional ou Casos de Uso: Modelagem/2.3.ModelagemOrganizacionalCasosDeUso.md
      - 2.4. Participações - Modelagem: Modelagem/2.4.ParticipacoesModelagem.md
      - 2.5. Iniciativas Extras - Modelagem: Modelagem/2.5.IniciativasExtras.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences